server:
  port: 8080
spring:
  application:
    name: KotlinSpringBoot

  #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/webapp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: wsymt1203
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0m
    timeout: PT30M
    database: 0

  security:
    user:
      name: admin
      password: 123
mybatis-plus:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: top.vicp.wsy19990317.dhxt.common.domain.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0
logging:
  config: classpath:logback.xml
